package org.pmcsn.model;

public enum EventType {
    ARRIVAL_PRE_SCORING,
    COMPLETION_PRE_SCORING,
    ARRIVAL_REPARTO_ISTRUTTORIE,
    COMPLETION_REPARTO_ISTRUTTORIE,
    ARRIVAL_SCORING_AUTOMATICO,
    COMPLETION_SCORING_AUTOMATICO,
    ARRIVAL_COMITATO_CREDITO,
    COMPLETION_COMITATO_CREDITO,
    ARRIVAL_REPARTO_LIQUIDAZIONI,
    COMPLETION_REPARTO_LIQUIDAZIONI,
    SAVE_STAT
}
